# Generated by Django 5.2.8 on 2025-11-24 09:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(80)], verbose_name='Возраст')),
                ('height', models.FloatField(verbose_name='Рост (см)')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, verbose_name='Пол')),
                ('goal', models.CharField(choices=[('weight_loss', 'Похудение'), ('muscle_gain', 'Набор мышечной массы'), ('strength', 'Развитие силы'), ('endurance', 'Выносливость'), ('health', 'Общее оздоровление')], max_length=20, verbose_name='Цель')),
                ('fitness_level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=20, verbose_name='Уровень подготовки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=10, verbose_name='День недели')),
                ('exercise_name', models.CharField(max_length=200, verbose_name='Упражнение')),
                ('sets', models.IntegerField(verbose_name='Подходы')),
                ('reps', models.CharField(max_length=50, verbose_name='Повторения')),
                ('rest_time', models.CharField(default='60 сек', max_length=50, verbose_name='Время отдыха')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='training_plans.userprofile')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
